Solea/Autonuoma/Controllers/AnswerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.Models;
using Org.Ktu.Isk.P175B602.Autonuoma.ViewModels;


namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers
{
	/// <summary>
	/// Controller for working with 'Modelis' entity.
	/// </summary>
	public class AnswerController : Controller
	{

		/// <summary>
		/// This is invoked when either 'Index' action is requested or no action is provided.
		/// </summary>
		/// <returns>Entity list view.</returns>
		public ActionResult Index()
		{
			var answers = AnswerRepo.List();
			return View(answers);
		}

		/// <summary>
		/// This is invoked when creation form is first opened in browser.
		/// </summary>
		/// <returns>Creation form view.</returns>
		public ActionResult Create(string q, int id)
		{
			//var answerEvm = new AnswerEditVM();
			var answerEvm = new AnswerEditVM();
			//PopulateSelections(answerEvm);
			answerEvm.Answer.fk_Questions=q;
			answerEvm.Lists.Questions_Id=id;
			var user=UserRepo.Find(Convert.ToInt32(TempData["id"]));
			answerEvm.Answer.fk_User=user.Name;
			answerEvm.user=user;
			return View(answerEvm);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the creation form.
		/// </summary>
		/// <param name="answerEvm">Entity model filled with latest data.</param>
		/// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Create(AnswerEditVM answerEvm, int id)
		{
			//form field validation passed?
			/*if( ModelState.IsValid )
			{
				AnswerRepo.Insert(answerEvm);

				//save success, go back to the entity list
				return RedirectToAction("Content", "Question", new { id = id, userId = answerEvm.user.Id});
			}*/
			if(answerEvm.Answer.Answers == null || answerEvm.Answer.Answers.Length < 3)
				ModelState.AddModelError("answer", "The answer must be atleast 3 characters long");
			else{
			AnswerRepo.Insert(answerEvm);
			//form field validation failed, go back to the form
			//PopulateSelections(answerEvm);
			return RedirectToAction("Content", "Question", new { id = id});
			}
			return View(answerEvm);
			//return View(answerEvm);
			
		}

		public ActionResult Like(int id, int idQ, string AnswerUserId)
		{
			var match = LikedRepo.Find(id, Convert.ToInt32(TempData["id"]), 0);
			var user = UserRepo.Find(AnswerUserId, 1);
			var Liked = LikedRepo.List();
			int LikedId = 0;
			if(Liked.Count==0)
				LikedId=1;
			else
				LikedId = LikedRepo.List().Last().Id+1;
			var answer=AnswerRepo.Find(id);
			if(match.AnswerId != id){
				answer.Answer.Likes+=1;
				if(user.Id!=Convert.ToInt32(TempData["id"]))
					user.Currency+=5;
				LikedRepo.Insert(0, id, Convert.ToInt32(TempData["id"]), LikedId, 1);
			}
			else if(match.likedOrDisliked == 2 ){
				answer.Answer.Likes+=1;
				answer.Answer.Dislikes-=1;
				if(user.Id!=Convert.ToInt32(TempData["id"]))
					user.Currency+=5;
				LikedRepo.Update(0, id, Convert.ToInt32(TempData["id"]), match.Id, 1);
			}
			else{
				if(user.Id!=Convert.ToInt32(TempData["id"]))
					user.Currency-=5;
				answer.Answer.Likes-=1;
				LikedRepo.Delete(match.Id);
			}
			UserRepo.Update(user);
			AnswerRepo.Update(answer);
			return RedirectToAction("Content","Question", new {id = idQ});
		}

		public ActionResult Dislike(int id, int idQ, string AnswerUserId)
		{
			var match = LikedRepo.Find(id, Convert.ToInt32(TempData["id"]), 0);
			var user = UserRepo.Find(AnswerUserId, 1);
			var Liked = LikedRepo.List();
			int LikedId = 0;
			if(Liked.Count==0)
				LikedId=1;
			else
				LikedId = LikedRepo.List().Last().Id+1;
			var answer=AnswerRepo.Find(id);
			if(match.AnswerId != id){
				answer.Answer.Dislikes+=1;
				LikedRepo.Insert(0, id, Convert.ToInt32(TempData["id"]), LikedId, 2);
			}
			else if(match.likedOrDisliked == 1 ){
				answer.Answer.Likes-=1;
				answer.Answer.Dislikes+=1;
				if(user.Id!=Convert.ToInt32(TempData["id"]))
					user.Currency-=5;
				LikedRepo.Update(0, id, Convert.ToInt32(TempData["id"]), match.Id, 2);
			}
			else{
				answer.Answer.Dislikes-=1;
				LikedRepo.Delete(match.Id);
			}
			UserRepo.Update(user);
			AnswerRepo.Update(answer);
			return RedirectToAction("Content","Question", new {id = idQ});
		}
		/// <summary>
		/// This is invoked when editing form is first opened in browser.
		/// </summary>
		/// <param name="id">ID of the entity to edit.</param>
		/// <returns>Editing form view.</returns>
		public ActionResult Edit(int id, string q, int id1)
		{
			var answerEvm = AnswerRepo.Find(id1);
			answerEvm.Answer.fk_Questions=q;
			answerEvm.Lists.Questions_Id=id;
			answerEvm.user=UserRepo.Find(Convert.ToInt32(TempData["id"]));
			//PopulateSelections(answerEvm);

			return View(answerEvm);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the editing form.
		/// </summary>
		/// <param name="id">ID of the entity being edited</param>
		/// <param name="autoEvm">Entity model filled with latest data.</param>
		/// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Edit(int id, AnswerEditVM answerEvm)
		{
			//form field validation passed?
			//if( ModelState.IsValid )
			//{
				if( answerEvm.Answer.Answers== null){
					ModelState.AddModelError("answer", "The answer cannont be empty");
					return View(answerEvm);
				}
				else if( answerEvm.Answer.Answers.Length < 3){
					ModelState.AddModelError("answer", "The answer must be at least 3 characters long");
					return View(answerEvm);
				}
				AnswerRepo.Update(answerEvm);

				//save success, go back to the entity list
				return RedirectToAction("Content","Question", new { id = id});
			//}

			//form field validation failed, go back to the form
			//PopulateSelections(answerEvm);
			//return View(answerEvm);
		}

		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view.</returns>
		public ActionResult Delete(int id, int idQ)
		{
			Answers answerLvm = new Answers();
			answerLvm.answer = AnswerRepo.FindForDeletion(id);
			answerLvm.user=UserRepo.Find(Convert.ToInt32(TempData["id"]));
			//answerLvm.question.Id=23;
			return View(answerLvm);
		}

		/// <summary>
		/// This is invoked when deletion is confirmed in deletion form
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view on error, redirects to Index on success.</returns>
		[HttpPost]
		public ActionResult DeleteConfirm(int id, int idQ)
		{
			//try deleting, this will fail if foreign key constraint fails
			try
			{
				AnswerRepo.Delete(id);

				//deletion success, redired to list form
				return RedirectToAction("Content","Question", new{id=idQ});
			}
			//entity in use, deletion not permitted
			catch( MySql.Data.MySqlClient.MySqlException )
			{
				//enable explanatory message and show delete form
				ViewData["deletionNotPermitted"] = true;
				Answers answerLvm = new Answers();
				answerLvm.answer = AnswerRepo.FindForDeletion(id);
				answerLvm.user=UserRepo.Find(Convert.ToInt32(TempData["id"]));
				answerLvm.question.Id=idQ;

				return View("Delete", answerLvm);
			}
		}

		/// <summary>
		/// Populates select lists used to render drop down controls.
		/// </summary>
		/// <param name="answerEvm">'Automobilis' view model to append to.</param>
		/*public void PopulateSelections(AnswerEditVM answersEvm)
		{
			//load entities for the select lists
			var users = UserRepo.List();

			//build select lists
			answersEvm.Lists.Users =
				users.Select(it => {
					return
						new SelectListItem() {
							Value = Convert.ToString(it.Name),
							Text = Convert.ToString(it.Name)
						};
				})
				.ToList();
             //load entities for the select lists
			/*var questions = QuestionRepo.List();

			answersEvm.Lists.Questions =
				questions.Select(it => {
					return
						new SelectListItem() {
							Value = Convert.ToString(it.Questions),
							Text = Convert.ToString(it.Questions)
						};
				})
				.ToList();
			
		}*/
	}
}

Solea/Autonuoma/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.Models;
using Org.Ktu.Isk.P175B602.Autonuoma.ViewModels;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;


namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers
{
	/// <summary>
	/// Controller for working with 'Marke' entity.
	/// </summary>
	public class UserController : Controller
	{
		/// <summary>
		/// This is invoked when either 'Index' action is requested or no action is provided.
		/// </summary>
		/// <returns>Entity list view.</returns>
		public ActionResult Index()
		{
			var users = UserRepo.List();
			return View(users);
		}

		/*public ActionResult Login(string name, string password)
		{
			var match = UserRepo.Find(darb.ID);
			return View(users);
		}*/
		//This page is invoked when login button is pressed
		public ActionResult Login()
		{
			return View();
		}

		//This function is invoked when a login form is submited (pressed login) on login page
		//It checks whether a user name and password is found in the data base
		//If found sends user's id to main page, so from there it can be used
		[HttpPost]
		public ActionResult Login(User user)
		{
			var match = UserRepo.Find(user);
			if( match.Name != user.Name || match.Password != user.Password )
				ModelState.AddModelError("password", "Incorrect name or password");
			if(match.Name == user.Name && match.Password == user.Password && user.Name!=null && user.Password !=null){
				TempData["id"]=match.Id;

				//Loggedin.Login();
				return RedirectToAction("Index", "Question");
				//return View( "Index", nameof(Index));
			}
			return View(user);
		}



		/// <summary>
		/// This is invoked when creation form is first opened in browser.
		/// </summary>
		/// <returns>Creation form view.</returns>
		public ActionResult Create()
		{
			var user = new User();
			return View(user);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the creation form.
		/// </summary>
		/// <param name="user">Entity model filled with latest data.</param>
		/// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Create(User user)
		{
			var matchName = UserRepo.Find(user.Name, 1);
			var matchEmail = UserRepo.Find(user.Email);
			// if(matchName.Name == "testasAI"){
			// 		Debug.WriteLine("gerai");
			// 	}
			// else
			// 	Debug.WriteLine("blogai");

			if( matchName.Name == user.Name)
				ModelState.AddModelError("name", "This name is already taken");
			else if( user.Name==null || user.Name.Length < 5)
				ModelState.AddModelError("name", "Name must be atleast 5 characters long");
			if( matchEmail.Email == user.Email)
				ModelState.AddModelError("email", "This email is already taken");
			else if( user.Email == null || user.Email.Length < 5)
				ModelState.AddModelError("email", "Email must be atleast 5 characters long");
			if(user.Password == null || user.Password.Length < 5)
				ModelState.AddModelError("password", "Password must be atleast 5 characters long");
			//form field validation passed?
			if (ModelState.IsValid && matchName.Name != user.Name && matchEmail.Email != user.Email)
			{
				// user.Currency=100;
				// UserRepo.Insert(user);
				// TempData["id"]=UserRepo.Find(user.Name, 1).Id;
				//matchName = UserRepo.Find(user.Name, 1);
				/*if(match.Name == "lab"){
					Debug.WriteLine("gerai");
				}
				else
					Debug.WriteLine("blogai");*/
				//save success, go back to the entity list

				int id = SendConfirm(user.Email);
				TempData["codeId"] = id;
				TempData["userN"] = user.Name;
				TempData["userE"] = user.Email;
				TempData["userP"] = user.Password;
				return RedirectToAction("Confirm");
				//return RedirectToAction("Index","Question");
			}

			//form field validation failed, go back to the form
			return View(user);
		}

		/// <summary>
		/// This is invoked when editing form is first opened in browser.
		/// </summary>
		/// <param name="id">ID of the entity to edit.</param>
		/// <returns>Editing form view.</returns>
		public ActionResult Edit()
		{
			var user = UserRepo.Find(Convert.ToInt32(TempData["id"]));
			return View(user);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the editing form.
		/// </summary>
		/// <param name="id">ID of the entity being edited</param>		
		/// <param name="marke">Entity model filled with latest data.</param>
		/// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Edit(User user)
		{
			//form field validation passed?
			if(user.Password == null || user.Password.Length < 5)
				ModelState.AddModelError("password", "Password must be at least 5 characters");
			else {
				UserRepo.Update(user);
				return RedirectToAction("Index","Question");
			}

			//form field validation failed, go back to the form
			return View(user);
		}
	
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view.</returns>
		public ActionResult Delete(int id)
		{
			var user = UserRepo.Find(id);
			return View(user);
		}

		/// <summary>
		/// This is invoked when deletion is confirmed in deletion form
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view on error, redirects to Index on success.</returns>
		[HttpPost]
		public ActionResult DeleteConfirm(int id)
		{
			//try deleting, this will fail if foreign key constraint fails
			try 
			{
				UserRepo.Delete(id);

				//deletion success, redired to list form
				return RedirectToAction("Index");
			}
			//entity in use, deletion not permitted
			catch( MySql.Data.MySqlClient.MySqlException )
			{
				//enable explanatory message and show delete form
				ViewData["deletionNotPermitted"] = true;

				var user = UserRepo.Find(id);
				return View("Delete", user);
			}
		}
		public int SendConfirm(string mail){
			using (MailMessage mm = new MailMessage("blokasthe@gmail.com", mail))
        {
			int id=0;
			Random random = new Random();
			id = random.Next();
            mm.Subject = "Account Activation";
            string body = "Hello " /*+ user.Name*/ + ",";
            body += "<br /><br />Please write the following code to activate your account: ";
			body += id;
            mm.Body = body;
            mm.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.EnableSsl = true;
            NetworkCredential NetworkCred = new NetworkCredential("blokasthe@gmail.com", "qrfeziedrxiiezll");
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = NetworkCred;
            smtp.Port = 587;
            smtp.Send(mm);
			return id;
        }
		}
		public ActionResult Confirm(){
			return View();
		}
		[HttpPost]
		public ActionResult Confirm(string code){
			string id = Convert.ToString(TempData["codeId"]);
			if(code == id){
				return RedirectToAction("Add");
			}
			TempData["codeId"] = id;
			return View();
		}
		public ActionResult Add(){
			User user = new User();
			user.Name = Convert.ToString(TempData["userN"]);
			user.Email = Convert.ToString(TempData["userE"]);
			user.Password = Convert.ToString(TempData["userP"]);
			user.Currency = 100;
			UserRepo.Insert(user);
			TempData["id"]=UserRepo.Find(user.Name, 1).Id;
			return RedirectToAction("Index", "Question");
		}
	}
}

Solea/Autonuoma/Views/_Layout.cshtml
@{
	/// <summary>
	/// Helper for marking active links in main menu.
	/// </summary>
	/// <param name="ctrl">Controller to look for.</param>
	/// <param name="act">Action to look for. Pass null if action does not matter.</param>
	/// <returns>If controller and (optionally) action match given ones returns "active". Returns empty string otherwise.</returns>
	@*string MarkActive(string ctrl, string act = null)
	{
		//get current controller and action
		var curCtrl = (string)ViewContext.RouteData.Values["Controller"];
		var curAct = (string)ViewContext.RouteData.Values["Action"];

		//compare to given ones
		if( curCtrl == ctrl && (act == null || curAct == act) )
			return "active";
		return "";
	}*@
	
}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Solea - @ViewData["title"]</title>
	<link rel="icon" type="image/x-icon" href="css/favicon.ico">
	<link rel="stylesheet" href="~/css/bootswatchTheme.css" />

	@*<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script> 

	<script src="@Url.Content("~/lib/datatables/datatables.js")"></script>

	<script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>*@
	
</head>
@*@if(TempData["id"]!=null){
			TempData["id"]=TempData["id"];	
}*@
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:5000/Question"><img src="/images/Solea-logos_whitee.png" width="170" height="auto" alt="logo"</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
	@*<script>
		sessionStorage.setItem("id", @TempData["id"]);
		if(sessionStorage.id == null || sessionStorage.id == 0)
	</script>*@
	@if(TempData["id1"]==null || Convert.ToInt32(TempData["id1"])==0){
	<span class="actions">
		<a href="@Url.Action("Create", "User")" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Register</a>
	</span>
	<span class="actions">
		<a href="@Url.Action("Login", "User")" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Login</a>
	</span>
	}
	else{
		<span class="actions">
			<a ><i class="fa-solid fa-plus"></i></a>
		</span>

		   <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
			   
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
				@*<antrast >@TempData["name"] </antrast>*@
					<ul class="nav nav-tabs">
 						<li class="nav-item dropdown">
    					<antrast class="btn btn-secondary btn-lg dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@TempData["name"] </antrast>
    						<div class="dropdown-menu" style="">
      							<a class="dropdown-item" href="@Url.Action("Edit", "User")">Edit profile</a>
      							<a class="dropdown-item" style="color: red;" href="@Url.Action("Index", "Home")">Logout</a>
  						</li>
					</ul>
				<img src="/images/gold.png" alt="golden" width="30" height="auto">x@(Convert.ToInt32(TempData["currency"])/100)
				<img src="/images/silver.png" alt="silver" width="30" height="auto">x@(Convert.ToInt32(TempData["currency"])%100/10)
				<img src="/images/bronze.png" alt="bronze" width="30" height="auto">x@(Convert.ToInt32(TempData["currency"])%10)
            </li> 
        </ul>
    </div>	
	}
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        @*<li class="nav-item">
          <a class="nav-link active" href="http://localhost:5000/Question">Questions
            <span class="visually-hidden">(current)</span>
          </a>
        </li>*@
        @*<li class="nav-item">
          <a class="nav-link" href="http://localhost:5000/Question/Create">Create a question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost:5000/Answer">Answers</a>
        </li>
		
        @*<li class="nav-item">
          <a class="nav-link" href="http://localhost:5000/User">Users</a>
        </li>*@
		
      </ul>
    </div>
  </div>
</nav>
		

	@* main menu*@
	<nav>
		<div>
			
			<div>
				<div>
					<ul>
						 @*
						<li>
							<a href="@Url.Action("Index", "User")" class="@MarkActive("User") nav-link">Users</a>
						</li>
						<li>
							<a href="@Url.Action("Index", "Question")" class="@MarkActive("Question") nav-link">Questions</a>
						</li>
						<li>
							<a href="@Url.Action("Index", "Answer")" class="@MarkActive("Answer") nav-link">Answers</a>
						</li>*@
					</ul>
				</div>
			</div>
		</div>
	</nav>

	@* main content gets rendered here *@
	<div class="main-content container-fluid">
		@RenderBody()
	</div>

	 @*page footer 
	<div class="container-fluid bg-dark text-muted">
		<div class="footer-wrapper container-fluid d-flex justify-content-center pt-2">
			<footer >
				<p>&copy; SOLEA</p>
			</footer>
		</div>
	</div>
	*@
	
	@* any javascript comming from script sections in views gets redered here *@
	@RenderSection("scripts", required: false)

	@* initialization routines go here *@
	<script type="text/javascript">
		//this function is run when page is fully loaded
		$(document).ready(function () {
			//apply datatables plugin on tables having css class 'entitylist'
			$(".entitylist").DataTable({
				"autoWidth": false,
				language : {
					"decimal":        "",
					"emptyTable":     "",
					"info":           "",
					"infoEmpty":      "",
					"infoFiltered":   "",
					"infoPostFix":    "",
					"thousands":      "",
					"lengthMenu":     "",
					"loadingRecords": "",
					"processing":     "",
					"search":         "Search:",
					"zeroRecords":    "",
					"paginate": {
						"first":      "",
						"last":       "",
						"next":       "",
						"previous":   ""
					},
					"aria": {
						"sortAscending":  ": rikiuoti didėjimo tvarka",
						"sortDescending": ": rikiuoti mažėjimo tvarka"
					}
				}
			});

			//apply datetimepicker plugin on date and datetime input fields
			$(".date-picker").datetimepicker({ timepicker:false, format: 'Y-m-d' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' });

			//Kadangi naudojamas vienas pasirinkimo objektas(SelectListItems) nustatyti pasirinkimo reikšmei reikia ja nustatyti panaudojant javascript funkcija ir html elementą
			@* $(".sel_element").each(function () {
				$(this).closest("td").find("select").val($(this).text());
			}); *@

			//Inicijuojami datos ir laiko pasirinkimo įvedimo elementai
			@* $(".date-picker").datepicker({ dateFormat: 'yy-mm-dd' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' }); *@

			@* $('input[type=text],input[type=radio],input[type=checkbox],textarea,select,input[type=email],input[type=number],input[type=datetime]').each(function () {
				var req = $(this).attr('data-val-required');
				var exclude = $(this).attr('data-exclude');
				if (undefined != req && undefined == exclude) {
					var label = $('label[for="' + $(this).attr('id') + '"]');
					var text = label.text();
					if (text.length > 0) {
						label.append('<span style="color:red"> *</span>');
					}
				}
			}); *@
		});
	</script>
	<script> src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>